### ISSUE TITLE
Is it possible to cancel SshCommand?

### ISSUE THREAD

**Issue by MistyKuu** [sshnet/SSH.NET#1023]
There is CancelAsync method but it seems to only cancel connection between client and server. Is there a way to stop the command from running? Similarly to CTRL+C while running in BASH shell.

**Comment by lifeincha0s** [comment]
No, using RunCommand, the Execute method blocks until all data is returned from the command, so nothing can be sent to stop the command. You need to use CreateShellStream to kill a running process, which allows writing data while reading data. You can then send Ctrl^C (\x3) to the output stream and kill the process.

**Comment by bsmithcompsci** [comment]
I solved this after a long day trying to force this to cancel, by hijacking the SSHCommand via reflection. This is nasty, please contributors/maintainers make a proper fix for this, this hurts production code. 

# Answer
```cs
token.Register(() => {
  FieldInfo? _sessionErrorOccuredWaitHandleField = sshCommand.GetType().GetField("_sessionErrorOccuredWaitHandle", BindingFlags.NonPublic | BindingFlags.Instance);
  if (_sessionErrorOccuredWaitHandleField != null)
  {
      object? _sessionErrorOccuredWaitHandle = _sessionErrorOccuredWaitHandleField.GetValue(sshCommand);
      MethodInfo[] methods = _sessionErrorOccuredWaitHandleField.FieldType.GetMethods();
      MethodInfo? Set = _sessionErrorOccuredWaitHandleField.FieldType.GetMethod("Set");
      if (Set != null)
          Set.Invoke(_sessionErrorOccuredWaitHandle, new object[] { });
  }
   sshCommand.CancelAsync();
   client.Disconnect();
});
```

# Diagnoses

To start, what's the issue. `EndExecute()` blocks the thread. This as expected to do, but we should be able to have a `CancellationToken` to cancel a asynchronous task. 

Using `CancelAsync()` just calls a dispose.... not greatly helpful. 
![image](https://github.com/sshnet/SSH.NET/assets/87924822/b2fef2fc-e07c-4f35-a886-57c7136c9310)

Okay, let's kill the client `Disconnect()`... nothing.... Well, let's understand how the Client communicates to the SSHCommand; we can see that the ctor of SSHCommand will append delegates for client callbacks.
![image](https://github.com/sshnet/SSH.NET/assets/87924822/3a0c48e2-8f17-4cac-b968-edc7d93346b6)
And we can see that, `Session_Disconnect()` calls something called `_sessionErrorOccuredWaitHandle.Set()`, which is interesting. 
![image](https://github.com/sshnet/SSH.NET/assets/87924822/2ac4eb54-d594-4a8f-ab5b-64f8b1839e29)
So, I believe there's a bug on the disposal of SSHCommand, when it comes to `_isDisposed` I cannot find exactly why, this may be the case.

Okay, so lets get our hands a little dirty. Let's touch the `AsyncWaitHandle` variable on `sshCommand` var. Well, we cannot simply `Close()` on the AsyncWaitHandle.... because that also will just do nothing.... 

But... while diving into SSH.NET code, I found something interesting that I can hijack with some reflection. 
**DONT TRY AT HOME** 
![image](https://github.com/sshnet/SSH.NET/assets/87924822/033960b2-54ce-47b8-9d30-65d9b899c3f0)

I can get around this problem today with some nasty hacks, but I hope in the future SSH.NET has a fix for this.
I hope this diagnoses was informational. Thanks, and take care!
