### ISSUE TITLE
Key exchange negotiation failed

### ISSUE THREAD

**Issue by okarpov** [sshnet/SSH.NET#1105]
Renci.SshNet.Common.SshConnectionException: Key exchange negotiation failed.
   at Renci.SshNet.Session.WaitOnHandle(WaitHandle waitHandle, TimeSpan timeout) in \SSH.NET-rsa-sha2-256\src\Renci.SshNet\Session.cs:line 977
   at Renci.SshNet.Session.WaitOnHandle(WaitHandle waitHandle) in \SSH.NET-rsa-sha2-256\src\Renci.SshNet\Session.cs:line 874
   at Renci.SshNet.Session.ConnectAsync(CancellationToken cancellationToken) in \SSH.NET-rsa-sha2-256\src\Renci.SshNet\Session.cs:line 739
   at Renci.SshNet.BaseClient.CreateAndConnectSessionAsync(CancellationToken cancellationToken) in \SSH.NET-rsa-sha2-256\src\Renci.SshNet\BaseClient.cs:line 545
   at Renci.SshNet.BaseClient.ConnectAsync(CancellationToken cancellationToken) in \SSH.NET-rsa-sha2-256\src\Renci.SshNet\BaseClient.cs:line 284
   at

**Comment by scott-xu** [comment]
Is the server OpenSSH 6.5 or 6.6? @okarpov

**Comment by okarpov** [comment]
ssh -V
OpenSSH_8.2p1 Ubuntu-4ubuntu0.8, OpenSSL 1.1.1f  31 Mar 2020

**Comment by scott-xu** [comment]
Then the case is different with mine. I got the same error message when connect to OpenSSH 6.6 and I believe it is caused by the wrong Bignum encoding in OpenSSH 6.5/6.6. OpenSSH fixed the issue in 6.7 (and 6.6.1). See https://www.openssh.com/txt/release-6.7
BTW, I think `ssh -V` is to display SSH client version but not server version.

**Comment by scott-xu** [comment]
> Then the case is different with mine. I got the same error message when connect to OpenSSH 6.6 and I believe it is caused by the wrong Bignum encoding in OpenSSH 6.5/6.6. OpenSSH fixed the issue in 6.7 (and 6.6.1). See https://www.openssh.com/txt/release-6.7 BTW, I think `ssh -V` is to display SSH client version but not server version.

Hi @WojciechNagorski, could we consider removing `curve25519-sha256` and `curve25519-sha256@libssh.org`  key exchange algorithms when speaking to OpenSSH 6.5 and 6.6? See https://github.com/openssh/openssh-portable/commit/9395b28223334826837c15e8c1bb4dfb3b0d2ca5

Alternatively, we could expose some event during negotiation so that the caller can attach a handler to the event and filter the key exchange algorithems.

Here's the line where we could add the filter logic: https://github.com/sshnet/SSH.NET/blob/develop/src/Renci.SshNet/Session.cs#L608

I can create PR if that's okay.

**Comment by scott-xu** [comment]
FYI, this is the root fix in OpenSSH: https://github.com/openssh/openssh-portable/commit/adbfdbbdccc70c9bd70d81ae096db115445c6e26

**Comment by WojciechNagorski** [comment]
@scott-xu can you create a new issue for this. I didn't know about this problem.

**Comment by scott-xu** [comment]
https://github.com/sshnet/SSH.NET/issues/1191 is created.

**Comment by WojciechNagorski** [comment]
Version 2023.0.0 has been published https://www.nuget.org/packages/SSH.NET/2023.0.0
