### ISSUE TITLE
Compression support

### ISSUE THREAD

**Issue by drieseng** [sshnet/SSH.NET#1130]
Even though **SSH.NET** supports compression, we do not ship with compression enabled.
We have a (stub-like) implementation of **zlib** compression in place which consists of the following classes:
* Renci.SshNet.Compression.Compressor
* Renci.SshNet.Compression.Zlib
* Renci.SshNet.Compression.ZlibOpenSsh
* Renci.SshNet.Compression.ZlibStream

The implementation of **ZlibStream** is commented out, and without this compression is of course broken.
I wasn't actively invoked in **SSH.NET** when this was decided, but I suppose this was done to avoid an extra dependency on a **zlib** library.

I see the following options for completing support for **zlib** (de)compression:
|Option|Advantages|Disadvantages|
|:-|:-|-|
|[ZipLibStream](https://learn.microsoft.com/en-us/dotnet/api/system.io.compression.zlibstream)|Supports RFC1950.|Only available in .NET 6+.|
|[DeflateStream](https://learn.microsoft.com/en-us/dotnet/api/system.io.compression.deflatestream)<sup>1</sup>|Supports wide range of TFMs.|Doesn't support RFC1950 header and trailer bytes.|
|Third-party **zlib** library<sup>2</sup>|Possible support wide range of TFMs.|Licensing.|

<sup>1</sup> We'll have to verify whether the lack of support for TFC1950 is a showstopper for [DeflateStream](https://learn.microsoft.com/en-us/dotnet/api/system.io.compression.deflatestream).
<sup>2</sup> If we decide to use a third-party library, we should move the **zlib** compression support to a separate library/assembly/nuget.

**Note:**
The difference between **zlib** and **zlib@openssh.org** is that the latter [delays](https://datatracker.ietf.org/doc/html/draft-miller-secsh-compression-delayed) compression until after user authentication.

**Comment by drieseng** [comment]
cc: @WojciechNagorski

**Comment by WojciechNagorski** [comment]
It's hard to tell now. First, we need to have integration tests. Then I would have to do some tests or POC because I don't have enough knowledge to say right now which option is better.

This is also related to another topic: which target frameworks we want to support. The .NET Framework is outdated and increases the cost of developing new functionalities. Even Microsoft does not release its frameworks for .NET Framework, for instance: EntityFramework Core, ASP Core, and so on. The old versions of those frameworks are not developed. So maybe we also make a mistake in that we want to support the old framework. We spend a lot of time developing and testing code for multiple target frameworks. What do you think?

Or maybe new features should only be developed for modern .NET if it's not easy to provide functionality for old .NET. In this case, we can use ZipLibStream only for modern .NET.
