### ISSUE TITLE
System.MissingMethodException: Cannot dynamically create an instance of type 'Renci.SshNet.Security.KeyExchangeECCurve25519'. Reason: No parameterless constructor defined.

### ISSUE THREAD

**Issue by Zero-Xiong** [sshnet/SSH.NET#1167]
Hi guys, what's the root cause?

Version:  2020.0.2

System.MissingMethodException: Cannot dynamically create an instance of type 'Renci.SshNet.Security.KeyExchangeECCurve25519'. Reason: No parameterless constructor defined.
   at Renci.SshNet.Session.WaitOnHandle(WaitHandle, TimeSpan)
   at Renci.SshNet.Session.Connect()
   at Renci.SshNet.BaseClient.CreateAndConnectSession()

**Comment by Rob-Hague** [comment]
Are you trimming your application?

**Comment by emetlashevskiy** [comment]
I have some error, how resolve it?
On win64 work fine, but on linux:
System.MissingMethodException: Cannot dynamically create an instance of type 'Renci.SshNet.Security.KeyExchangeECCurve25519'. Reason: No parameterless constructor defined.
   at Renci.SshNet.Session.WaitOnHandle

**Comment by emetlashevskiy** [comment]
Yes, if untrimmed app when work fine!
You need set "PublishTrimmed" to false, or remove from *.csproj.

**Comment by emetlashevskiy** [comment]
Another problem, how disable trimming my app if PublishAOT is true?
I tryed 	  

```
<PackageReference Include="SSH.NET" Version="2020.0.2">
    <IsTrimmable>false</IsTrimmable>
</PackageReference>
```

but no effect.

**Comment by Rob-Hague** [comment]
I don't know a lot about trimming. I think you may try "rooting" the assembly as described at this link

https://learn.microsoft.com/dotnet/core/deploying/trimming/trimming-options?pivots=dotnet-7-0#root-assemblies

(untested)

```xml
<ItemGroup>
  <TrimmerRootAssembly Include="Renci.SshNet" />
</ItemGroup>
```

You could even try using "descriptors" to preserve just the specific types listed here:

https://github.com/sshnet/SSH.NET/blob/004b57ae9e7ca07f12e7192d7987a8e5d950b04c/src/Renci.SshNet/ConnectionInfo.cs#L344-L357

---

I can't see a way on the library side to mark it as incompatible with trimming, short of fixing the actual problem which is the use of reflection here:

https://github.com/sshnet/SSH.NET/blob/004b57ae9e7ca07f12e7192d7987a8e5d950b04c/src/Renci.SshNet/ServiceFactory.cs#L93

It would probably be fixed by changing `ConnectionInfo.KeyExchangeAlgorithms` to `Dictionary<string, Func<IKeyExchange>>` instead of `Dictionary<string, Type>`

**Comment by Zero-Xiong** [comment]
> PublishTrimmed

Thanks for comment!
