### ISSUE TITLE
Terrapin attack and strict KEX

### ISSUE THREAD

**Issue by DavisNT** [sshnet/SSH.NET#1285]
There is a recently published attack on SSH named [Terrapin](https://terrapin-attack.com/).

Is SSH.NET affected by Terrapin (does SSH.NET support any of the vulnerable encryption modes; does SSH.NET support the strict key exchange countermeasure)?

**Comment by Rob-Hague** [comment]
The library does not support ChaCha20-Poly1305 nor Encrypt-then-MAC (for better or worse), and does not support SSH extension negotiation (RFC8308)

**Comment by edwinvandeburgt** [comment]
Will Encrypt-then-MAC be supported (and when)?

Because one of the major cloud provider's SFTP-service isn't working anymore with the proposed security profile:

[Amazon AWS FTPS policy](https://docs.aws.amazon.com/transfer/latest/userguide/security-policies.html#security-policy-transfer-2022-03)

Profile 2022-03 still support the "normal" hashfunctions:
`    "SshMacs": [
      "hmac-sha2-512-etm@openssh.com",
      "hmac-sha2-256-etm@openssh.com",
      "hmac-sha2-512",
      "hmac-sha2-256"
    ],`

With profile 2023-05, only the EtM versions are supported:
`        "SshMacs": [
            "hmac-sha2-512-etm@openssh.com",
            "hmac-sha2-256-etm@openssh.com"
        ],`

Do you have a policy regarding attempting to remain compatibility of the library with the major Cloud providers Microsoft, Amazon and Google?

**Comment by DavisNT** [comment]
@scott-xu, @Rob-Hague Thank you very much!
