### ISSUE TITLE
Allow writing to stdin of SshCommand

### ISSUE THREAD

**Issue by hifi** [sshnet/SSH.NET#141]
SshCommand doesn't currently implement any way to write a long binary stream into stdin of the executed process.

SshCommand would need an `InputStream` property that would provide a writable stream which would also send the EOF packet when closed by the writer.

**Comment by hifi** [comment]
PR #144 now implements this.

**Comment by 21region** [comment]
Could you, please, provide a high level view of how this will be used?
I'm interested in this feature, because it looks like it will allow to do on-the-fly decompression.

**Comment by hifi** [comment]
There's the other PR that is more alive than this one (for stdout/stderr). The general idea is that you use streams to communicate with a remote process like you would on the local machine like with [System.Diagnostics.Process](https://msdn.microsoft.com/en-us/library/system.diagnostics.process(v=vs.110).aspx) with the stream properties StanardInput/StandardOutput/StandardError.

**Comment by dosvidos** [comment]
It's quite embarrassing that SSH.NET doesn't redirect **stdin** for remotely **exec**uted command.
This functionality is supported by Open SSH server and popular SSH client libraries like [Paramiko](https://github.com/paramiko/paramiko)

**Comment by realvizu** [comment]
I have a fork that implements this feature. Shall I submit a PR for it?
I mean, would there be someone willing to review and merge it?

I'm asking because I think that there are already 2 dead PRs about this subject: #144 and #1052 .
I'm not sure what went wrong with those PRs so that they were never merged and I'd like to avoid falling into the same trap.
Maybe the scope of those PRs were too big by introducing a few new types that were not necessary for the feature? (Pipe, LinkedListQueue, etc.)
My PR would contain only the bare minimum for the feature: the ChannelInputStream class and the SshCommand.InputStream property.

**Comment by WojciechNagorski** [comment]
You should definitely create a new pull request. Previous pull requests do not pass unit and integration tests.

This change is really important for me so if you create a pull request it will be on the first place on my list.

**Comment by realvizu** [comment]
@WojciechNagorski Please check out this PR: https://github.com/sshnet/SSH.NET/pull/1293

**Comment by realvizu** [comment]
@WojciechNagorski Thanks for merging the PR! 
Any plans about when a new nuget version will be released?

**Comment by WojciechNagorski** [comment]
Fixed by #1293
