### ISSUE TITLE
Infinite timeout on async UploadFile with OpenAsync/CopyToAsync

### ISSUE THREAD

**Issue by Dunge** [sshnet/SSH.NET#1497]
I'm using the code here https://github.com/sshnet/SSH.NET/pull/819#issuecomment-1003769248 to have an async upload file and it works.

Unfortunately, if I'm uploading a file and close the connection on the remote end, the method will never finish. I would be expecting some exception to be thrown. Instead the thread remains stuck indefinitely, and it's not a good thing for server-side process doing this operation in batches.

I found [this decade old question](https://stackoverflow.com/questions/25736589/sftp-upload-using-sshnet-library-handling-connection-issues) and tried to set the `OperationTimeout` property to 30sec, but it doesn't seems to have any effect.

I'm aware I can have a CancellationToken, but this would be a way for me to trigger a cancellation from my end, not one that happens when the connection get closed remotely or if a timeout happen.

**Comment by Rob-Hague** [comment]
I think the problem is that the non-async methods in `SftpSession` are checking on a few wait handles which can throw errors:

https://github.com/sshnet/SSH.NET/blob/82246e3cc929945461cba9c2481fb9778b7e4618/src/Renci.SshNet/Sftp/SftpSession.cs#L936

https://github.com/sshnet/SSH.NET/blob/82246e3cc929945461cba9c2481fb9778b7e4618/src/Renci.SshNet/SubsystemSession.cs#L224-L232

But the async methods are not. They should at least (do something like) subscribe to the same events where those wait handles are set

**Comment by Dunge** [comment]
Thank you very much for this first analysis, you seems to be on to something.

At least it confirms that it's not just me using the lib incorrectly or missing a configuration parameter somewhere.

I assume it's not as simple as adding that same call in the async methods since it's using streams and probably can't subscribe to events the same way. I would love to continue on your investigation work and submit a PR, but I unfortunately do not trust my knowledge enough to fix it properly.

**Comment by Rob-Hague** [comment]
No problem, yeah I don't think it's quite that simple but I might have a solution which is not too dissimilar
