### ISSUE TITLE
ED25519Key PrivateKey doesnt return all bytes

### ISSUE THREAD

**Issue by darinkes** [sshnet/SSH.NET#1548]
Noticed after updating my SshNet.Agent Extension to the current 2024.2.0-Release
2024.1.0 is fine, though.

I would guess it could be fallout from: https://github.com/sshnet/SSH.NET/pull/1448

Please also see: https://github.com/darinkes/SshNet.Agent/issues/8

**Comment by darinkes** [comment]
Chaos.Nacl (old):
```
public static readonly int ExpandedPrivateKeySizeInBytes = 32 * 2;

PrivateKey = new byte[Ed25519.ExpandedPrivateKeySizeInBytes];
```

BouncyCastle (new):
```
public static readonly int SecretKeySize = 32;

PrivateKey = new byte[Ed25519.SecretKeySize];
```

The size of the privatekey byte array is too small now.

Diff could be something like that:
```
--- a/src/Renci.SshNet/Security/Cryptography/ED25519Key.cs
+++ b/src/Renci.SshNet/Security/Cryptography/ED25519Key.cs
@@ -86,7 +86,7 @@ public ED25519Key(SshKeyData publicKeyData)
             }
 
             PublicKey = publicKeyData.Keys[0].ToByteArray(isBigEndian: true).TrimLeadingZeros().Pad(Ed25519.PublicKeySize);
-            PrivateKey = new byte[Ed25519.SecretKeySize];
+            PrivateKey = new byte[Ed25519.SecretKeySize * 2];
         }
 
         /// <summary>
@@ -97,9 +97,9 @@ public ED25519Key(SshKeyData publicKeyData)
         /// </param>
         public ED25519Key(byte[] privateKeyData)
         {
-            PrivateKey = new byte[Ed25519.SecretKeySize];
+            PrivateKey = new byte[Ed25519.SecretKeySize * 2];
             PublicKey = new byte[Ed25519.PublicKeySize];
-            Buffer.BlockCopy(privateKeyData, 0, PrivateKey, 0, Ed25519.SecretKeySize);
+            Buffer.BlockCopy(privateKeyData, 0, PrivateKey, 0, Ed25519.SecretKeySize * 2);
             Ed25519.GeneratePublicKey(privateKeyData, 0, PublicKey, 0);
         }
```
I couldn't find a reasonable BouncyCastle constant.

With this patch ED25519 works again in the SshNet-Extensions.

**Comment by Rob-Hague** [comment]
Looks reasonable, do you want to put up a PR?

**Comment by scott-xu** [comment]
What specific issue if the Ed25519 private key length is 32?

**Comment by scott-xu** [comment]
Is the next 32 bytes public key?

**Comment by scott-xu** [comment]
> Is the next 32 bytes public key?

The answer is yes.

```C#
var privateKey = Convert.FromHexString("92-F0-5A-EA-18-A5-F3-08-92-B5-66-DD-A6-A4-CC-51-64-D0-66-39-B4-DF-B4-0A-84-1C-76-00-30-A3-F2-BC".Replace("-", string.Empty));
var publicKey = new byte[Ed25519.PublicKeySize];
Ed25519.GeneratePublicKey(privateKey, publicKey);
Console.WriteLine(Convert.ToHexString(publicKey));
```
Output:
4E56E8170D9CCB8D80B62E51AD7C17F0A2F1DCCFA9E20EFC7DF7DE7D32BF8A3A

**Comment by darinkes** [comment]
> What specific issue if the Ed25519 private key length is 32?

The issue is if you want to export your private key e.g. in to the SSH Agent or into openssh keyfile it will get rejected as malformed.

Sure, I could workaround this by appending the pub key myself to the private key bytes, but I think its an API breaking change and  should behave like it did before.

**Comment by Rob-Hague** [comment]
agree, the behaviour should be preserved

**Comment by darinkes** [comment]
@Rob-Hague I thought about opening an PR, but I'm not sure if there is a "good" BouncyCastle constant for this size.
Maybe it could be `SecretKeySize + PublicKeySize`, not sure....

**Comment by scott-xu** [comment]
I would agree if there's no `PublicKey` property in `ED25519Key` class.
https://github.com/sshnet/SSH.NET/blob/3b4f2cfc1c6c0da935faf1c601b20026dceda473/src/Renci.SshNet/Security/Cryptography/ED25519Key.cs#L65-L73

Regarding OpenSSH private key format, the value contains both private key and public key.
https://datatracker.ietf.org/doc/html/draft-miller-ssh-agent-11#section-3.2.3

> The second value is a concatenation of the private key k and the public ENC(A) key.

Regarding PuTTY PPK format, the Ed25519 public key and private key are separated:
https://tartarus.org/~simon/putty-snapshots/htmldoc/AppendixC.html#ppk-privkey-eddsa

> The public key data has already provided the public elliptic curve point. The private key stores:
> - mpint: the private exponent, which is the discrete log of the public point.

Regarding PKCS#8 format, the private key is solely private key.
https://www.rfc-editor.org/rfc/rfc5208#section-5
rfc5958 defines extra optional public key field, and has status "proposed standard".
Some interesting discussion: https://www.rfc-editor.org/rfc/rfc5958

In a word, I don't think we should revert to the wrong length just because it was there for long time.

How about add another constructor for `ED25519Key` class which takes both private key bytes and public key bytes? @darinkes 
See my recent comments please: https://github.com/sshnet/SSH.NET/pull/1543#discussion_r1855201036

**Comment by darinkes** [comment]
K, will do it myself then.
