### ISSUE TITLE
executing telnet command , result empty

### ISSUE THREAD

**Issue by rakeshkhoodeeram** [sshnet/SSH.NET#205]
hello,
I can connect to server with
```
var connectionInfo = new KeyboardInteractiveConnectionInfo(ip, 22, username);
                connectionInfo.AuthenticationPrompt += delegate (object sender, AuthenticationPromptEventArgs e)
                {
                    foreach (var prompt in e.Prompts)
                    {
                        if (prompt.Request.Equals("Password: ", StringComparison.InvariantCultureIgnoreCase))
                        {
                            prompt.Response = "password";
                        }
                    }
                };
```
but when i try executing telnet command, I do not seem to succeed. (maybe i should run async or wait)
```
var sshclient = new SshClient(connectionInfo)
 var terminal = sshclient.RunCommand("telnet xxx.xxx.xxx.xx 9819" + Environment.NewLine);
                            log.Info("Command>" + terminal.CommandText);
                            log.Info("Result>" + terminal.Result);
```

after telnet, i execute other commands and all of them fails (error: unknown command, i presume the telnet command failed, so the following ones also fail)

**Comment by keyoti** [comment]
If you run something basic like 'ls' does it still report unknown command?  Just wondering if it's actually telnet that's giving the error, not ssh.

**Comment by kasbst** [comment]
@rakeshkhoodeeram could you please provide more details and answer to @keyoti question?

**Comment by darkoperator** [comment]
This is because you are using RunCommand when you establish a connection you do not start a shell on the host, for that after connection you will need to create a stream from the connection, this will create a terminal that you can issue and read from. RunCommand will simply do an exec on the system and close the process so it calls the telnet command and closes it and then you are sending other commands thinking that the connection retains a state.
