### ISSUE TITLE
Multithreading

### ISSUE THREAD

**Issue by hazar34** [sshnet/SSH.NET#215]
Hi! I'm using this library to run queries on few client VDS, and I found that execution does not work in multiple threads. Work in a multithreaded mode is blocked by functions like AuthenticationConnection.Wait()
Is it possible to make a real multithreading?

**Comment by baldec** [comment]
I would second this. 

We are currently monitoring nodes that only have ssh access using this. And thus we open a connection to the nodes and just monitor if it goes down or not. And on certain criterias we take action.

The issue is that when monitoring a large amount of nodes, and the connectivity goes down then reconnect is attempted against all nodes. And instead of trying against all nodes(or the thread limitation) at once it takes a few, wait for the timeout, takes a few and so on.

It would be lovely if it would be possible to improve the library so that this limitation was removed.

**Comment by Rob-Hague** [comment]
The AuthenticationConnection semaphore has been removed in #1304

**Comment by WojciechNagorski** [comment]
This issue has been fixed in the 2024.0.0 version.
