### ISSUE TITLE
'No Such File' during client.CreateDirectory(path)

### ISSUE THREAD

**Issue by AlanGreyjoy** [sshnet/SSH.NET#327]
I am trying to create directories in our CentOS server and I get thrown an exception. 'No Such File'

Now, this doesn't happen all the time, only sometimes. But when it starts, it doesn't go away for a couple of days.

savePath = "/PhoneManager/Help/Pages/Phones/Adding_Extensions/";
if (!client.Exists(savePath))
                        {
                            client.CreateDirectory(savePath);
                        }

**Comment by drieseng** [comment]
Are you sure it's only the last part of the path that does not exist?
This may not be the case for all SFTP servers, but in general `CreateDirectory(String)` (**SSH_FXP_MKDIR**) will only create the specified directory. It will not create any missing parent directories.

**For example:**
If you attempt to create **"/PhoneManager/Help/Pages/Phones/Adding_Extensions"**, it will only succeed if the **"/PhoneManager/Help/Pages/Phones"** path already exists.

**Comment by jehrenzweig** [comment]
@AlanGreyjoy I suspect it's because `SftpClient.Exists()` is bugged and cannot reliably determine if a directory exists when the path begins with a forward-slash character (`/`).  Your `savePath` value (`/PhoneManager/Help/Pages/Phones/Adding_Extensions/`) does appear to fit that use-case. Could you do me a favor and try using the same value without the leading slash (i.e. `PhoneManager/Help/Pages/Phones/Adding_Extensions/`) and see if that workaround fixes things for you?

**Comment by drieseng** [comment]
No feedback.

**Comment by EngrKhizarIqbal** [comment]
Hi, is there a way to create nested directories?
