### ISSUE TITLE
Documentation seems basically non-existant

### ISSUE THREAD

**Issue by evilC** [sshnet/SSH.NET#418]
The only docs I can find are [on the CodePlex site](https://archive.codeplex.com/?p=sshnet) which consists of a zip (The "SshClient.chm" link just points to the same page).  
The zip is basically useless. Absolute links to `C:/wikipage`, blank files, examples with wrong parameter order, etc, etc.  
Am I missing something? Is there more complete documentation somewhere?

**Comment by Blizzardo1** [comment]
I agree. Documentation is very important, ESPECIALLY for SSH.

**Comment by iursevla** [comment]
Same issue here...

**Comment by LanceUMatthews** [comment]
There is MSDN-style class documentation in a `.chm` file for each release, which you can find on the [GitHub releases page](/sshnet/SSH.NET/releases).

**Comment by SuperJMN** [comment]
Please, give sample usages of the SshClient. I would like to run a set of commands in the SAME session, but it seems the client runs every command in a new session.

**Comment by codex-nz** [comment]
Hate to jump on the band wagon but docs (not those generated by GhostDoc) would be super awesome.
Having issues trying to get commands to even execute properly in some cases but there is nothing to refer to in order to figure out if I am using the correct commands, sequences, etc.
Have found there are multiple ways to use SSH related classes and functionality but again, no docs to tell me if I should be doing this and if there are any side effects or caveats to this approach.

Great job on the code, would be even better if there were docs to go with it.

**Comment by mmoo9154** [comment]
This issue is strongly related to [Issue# 176](https://github.com/sshnet/SSH.NET/issues/176).  I'm not sure which should be closed as duplicate, but this one has more comments.

How do we escalate this, and how can we help? @drieseng asked for a pull request in #176 so I'm going to make a PR on the README.md.  Fingers crossed that it gets accepted after Gert is finished cleaning @rickerj135's clothing in Stuttgart.  😉

If community edits to README.md is not the way to go, at the very least **PLEASE** add a link to the latest help.chm file to the front page README.md in the **Introduction** section (along with a note telling people they need to [right-click and "unblock"](https://support.microsoft.com/en-us/help/2021383/some-chm-files-may-not-render-properly-on-windows-vista-and-windows-7)).

As a number of people have commented, the code seems to be very well written.  This means there must be some well written design documents **_somewhere_**.

@drieseng what have you been using as design docs?  The README.md says this implementation is based on a Sharp.SSH library.  I'm happy to start from documentation for a library based in any other project or any other language. I just want to make sure I'm looking at the same docs you have been using as you have been jamming on this awesome (imho) project.

**Comment by darkoperator** [comment]
Why not switch to markdown help or the wiki?

**Comment by mmoo9154** [comment]
> Why not switch to markdown help or the wiki?

I think only @drieseng can do it, but someone should open up the [project wiki](https://github.com/sshnet/SSH.NET/wiki) for public editing: https://help.github.com/en/github/building-a-strong-community/changing-access-permissions-for-wikis

**Comment by DanielHabenicht** [comment]
In the latest release there is no `.chm` file anymore? Is this by error?

**Comment by drieseng** [comment]
@WojciechNagorski, didn't you use the MSBuild script to build the release?

**Comment by WojciechNagorski** [comment]
Yes. I have to upload it. But right now I don't have too much free time. I will be able to do it next week.

**Comment by Rob-Hague** [comment]
https://sshnet.github.io/SSH.NET/
