### ISSUE TITLE
Renci.SshNet.Common.SshAuthenticationException: Permission denied (password).

### ISSUE THREAD

**Issue by kranz912** [sshnet/SSH.NET#437]
I did a build using NET 4.7 and it gives me this error
![image](https://user-images.githubusercontent.com/18607656/41175010-b6df4a50-6b29-11e8-9e59-0324eda406d1.png)

**Comment by DanielVukelich** [comment]
From the xml documentation of SftpClient.Connect():
`<exception cref="SshAuthenticationException">Authentication of SSH session failed.</exception>`

That means SshAuthenticationException is thrown when you call client.Connect() because you're using the wrong password.  Make sure you have the right one.

You should also surround the Connect() call with a try/catch statement, so that you can present the user with a useful error message, instead of crashing the application when they use the wrong password (or if another exception is thrown when trying to connect).

**Comment by drieseng** [comment]
Please reopen this issue if you need more help.

**Comment by MadhanRamachandran** [comment]
Hi,

We are getting below error in SFTP connection in D365 FO local one box environment.  

Please advice on the same.

Microsoft.Dynamics.Ax.Xpp.ClrErrorException: SshAuthenticationException ---> Renci.SshNet.Common.SshAuthenticationException: Permission denied (keyboard-interactive). at Renci.SshNet.ClientAuthentication.Authenticate(IConnectionInfoInternal connectionInfo, ISession session) at Renci.SshNet.ConnectionInfo.Authenticate(ISession session, IServiceFactory serviceFactory) at Renci.SshNet.Session.Connect() at Renci.SshNet.BaseClient.Connect() at

**Comment by SaebAmini** [comment]
This one was doing my head in. It turned out some servers do not support `PasswordAuthenticationMethod`, so you'll have to use `KeyboardInteractiveAuthenticationMethod`, and then handle the `AuthenticationPrompt` event to provide the password:

```C#
var authMethod = new KeyboardInteractiveAuthenticationMethod("Username");
authMethod.AuthenticationPrompt += (sender, e) =>
{
    e.Prompts.Single().Response = "Password";
};
var connectionInfo = new ConnectionInfo("host", 22, "Username", authMethod);

using (var client = new SftpClient(connectionInfo))
{
    client.Connect();
    // ...
}
```
