### ISSUE TITLE
ScpClient.Upload and ScpClient.Download hang against the Cisco NCS 5500

### ISSUE THREAD

**Issue by ahelwer** [sshnet/SSH.NET#451]
Chassis: https://www.cisco.com/c/en/us/products/routers/network-convergence-system-5500-series/index.html

OS: Cisco IOS XR, Version 6.1.3

Possibly related to #414 

I created a small program which does the following:

```
using (ScpClient client = new ScpClient(address, username, password))
{
    client.Connect();
    using (Stream localFile = File.OpenRead(localFilePath))
    {
        client.Upload(localFile, remoteFilePath);
    }
}
```
Using a debugger, I traced the hang to the following place (using the latest changes in master at time of posting):

```
Upload (line 207 of ScpClient.cs)
UploadFileModeAndName (line 295 of ScpClient.cs, called from line 225 of ScpClient.cs)
CheckReturnCode (line 394 of ScpClient.cs, called from line 298 of ScpClient.cs)
ReadByte (line 421 of ScpClient.cs, called from line 396 of ScpClient.cs)
Read (line 181 of PipeStream.cs, called from line 423 of ScpClient.cs)
```

The program then hangs at the call to `Monitor.Wait(_buffer);` on line 204 of PipeStream.cs.

The SCP server on the devices I've tested against is up and working, confirmed with PuTTY's SSH tool pscp. I can upload & download without issue using the same credentials. I have also run my SSH.NET program against devices other than the Cisco NCS 5500, and it works just fine.

I am trying to debug the issue myself as it's blocking me, but would love some assistance!

**Comment by drieseng** [comment]
Some embedded devices only report SCP errors using stderr instead of stdout.
This is not something we currently take into account, and we currently wait indefinitely when we get no response via stdout. I'm pretty sure that is what's causing the "hang" in your situation.

Now as to why the device is probably reporting an error, I think it probably because we're sending a quoted path and the Cisco device it not particularly fond of that.

I suggest you try the **ShellQuote** or **None** path transformation. More info on that is available [here](https://github.com/sshnet/SSH.NET/wiki/ScpClient:-Remote-path-transformation).

**Note:**
You need SSH.NET 2016.1.0 for this.

**Comment by ahelwer** [comment]
THANK YOU!!!! That fixed it - we used RemotePathTransformation.None and it worked!

**Comment by drieseng** [comment]
Glad I could help you.
I'll close this issue, and create a new issue for detecting and reporting such issues.
