### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by TFTomSun** [sshnet/SSH.NET#552]
I found some issues, but at least the last nuget package is from 2016. Is this project still maintained? Does it make sense to write the issues?

**Comment by Deantwo** [comment]
Didn't you just write an issue anyway? Rather than write this it would be more interesting to know what the issue is. Even if the project isn't officially maintained by the original author, someone else can fork it and fix it if you just report the issue.

The wonders of open-source lets us fix the code ourselves.

**Comment by drieseng** [comment]
I have not abandoned this project, but I'm afraid I have very little time to do any OSS work.
Right now, I'm focusing on a big update for **Ninject**.
Once that is done, I hope to have more time for **SSH.NET**.

**Comment by drieseng** [comment]
I'm getting there ... :p
