### ISSUE TITLE
Server response does not contain SSH protocol identification

### ISSUE THREAD

**Issue by folibis** [sshnet/SSH.NET#571]
The test code is:

```
using (SshClient ssh = new SshClient(host, 22, "root", "root"))
{
     ssh.Connect();
     SshCommand response = ssh.RunCommand(command);      
     string response =  response.Result;
}
```

I can connect with Putty w/o any problem. Connection from VC cause to the error from the title.

**Comment by JohnLBevan** [comment]
It's possible that this behavior could be caused by a firewall on the SFTP server's side / them rejecting your request as your IP's not whitelisted.  Looking at a WireShark trace when we've seen this issue I see [FIN, ACK] returned by the server; implying that they're requesting the termination.

**Comment by readonlymaio** [comment]
Late to the party but, I just to inform that i had the same (random) issue and it was caused by MaxStartUps parameter on the ssh/sftp server side. The sftp server was exposed on the internet with no source ip blocking... if the number of non authenticated connection exceedes the MaxStartUps the sftp server drops any new connection and you get "Server response does not contain SSH protocol identification"
