### ISSUE TITLE
Incorrect passphrase throws non consistent exception

### ISSUE THREAD

**Issue by aeroboy86** [sshnet/SSH.NET#581]
Hello,
I am trying to implement private key based login to my SSH server. When I try to instantiate a PrivKeyFile(string filename, string passphrase), if I pass an incorrect passphrase for the supplied keyfile I get inconsistent exceptions thrown. 

I would expect "Invalid Passphrase" but often I get an exceptions relating to DER length.

I know the KeyFile is correct as I can establish a connection when I provide the correct passphrase for the same key/user. I am just trying to make the application robust and presenting an obscure message to the user is not desirable.

Any suggestions would be greatly appreciated. 

Thanks in advance

**Comment by aeroboy86** [comment]
For more context, the exceptions that are being thrown appear to be either of the following:

https://github.com/sshnet/SSH.NET/blob/bd01d971790a7c1fa73bad35b79ada90bf69e62d/src/Renci.SshNet/Common/DerData.cs#L104

https://github.com/sshnet/SSH.NET/blob/bd01d971790a7c1fa73bad35b79ada90bf69e62d/src/Renci.SshNet/Common/DerData.cs#L289

Noting that this occurs if I provide an incorrect passphrase for a private key file and does not occur if I provide a correct passphrase.

I would have expected possibly the following exception to be thrown:

https://github.com/sshnet/SSH.NET/blob/bd01d971790a7c1fa73bad35b79ada90bf69e62d/src/Renci.SshNet/PrivateKeyFile.cs#L239

**Comment by aeroboy86** [comment]
Any thoughts other than filtering issues and blanketly putting it down to the incorrect passphrase?

**Comment by ghost** [comment]
I'm not really familiar with the SSH.NET internals so I might be wrong, but it is impossible to tell with 100% confidence whether the failure to decrypt the private key is due to an incorrect passphrase or to the key data being corrupted.
This is because any passphrase, either correct or wrong, results in a valid 3DES key to be used for decrypting the private key. Decrypting with a "wrong" 3DES key will always succeed, but with a corrupted plaintext private key which is indistinguishable from a corrupted encrypted private key decrypted with a "correct" 3DES key.
So there is no solution to your problem (inconsistent error reporting) other than either attributing all the private key errors to incorrect passphrases or to corrupted key files, I think.

**Comment by aeroboy86** [comment]
Thanks for the feedback @sadlame. As I mentioned the only variable that I was changing was the passphrase string that I was providing to decrypt the file therefore I will just modify my exception handler to provide a generic message that the private key failed to decrypt with the passphrase provided.

Thanks for your information on the mechanism of how the key is handled.
