### ISSUE TITLE
Message type 60 is not valid in the current context

### ISSUE THREAD

**Issue by mh-rgebis** [sshnet/SSH.NET#604]
I have been using ssh.net version 2016.0.0 for few months and it was working just fine. Last night our remote ssh server was upgraded which caused issues connecting.
As of today, I am getting Exception on Connect() and this is the message.
"Message type 60 is not valid in the current context". I see that other people reported similar issue but instead of 60, they got 80. Latest 2016.1.0 generate same Exception on Connect(). 
Do any other people see this? What does 60 stand for?

**Comment by mh-rgebis** [comment]
Never mind. I figured it out. 60 is SSH_MSG_USERAUTH_PASSWD_CHANGEREQ

**Comment by Thorium** [comment]
Is there a way how SSH.NET would support changing the password at login if expired?

Edit: Found it: Instead of using `SftpClient` with credentials directly, use overload that takes `PasswordConnectionInfo` object as parameter, that object has `PasswordExpired` event handler where you can bind a function taking args and changing the `NewPassword` property of those args.
