### ISSUE TITLE
A non-recoverable error occurred during a database lookup

### ISSUE THREAD

**Issue by shawndewet** [sshnet/SSH.NET#808]
Here is the relevant code snippet:
```
using (var client = new SshClient(hostName, userName, new PrivateKeyFile(fileName)))
{
  client.Connect();

```

I'm getting the mentioned error on the `client.Connect()` method call, like so:
![image](https://user-images.githubusercontent.com/1556343/115022785-28c66e80-9ebe-11eb-8ac4-f3be508c46e3.png)

Are there any pointers as to how to get more information about this error? Where does one begin to start digging for more detail?

Interesting note is that I get this error _even if I enter a bad hostName (a host that does not exist)_, which tells me that this error has nothing to do with the server-side...the call isn't even getting to the server.

**Comment by darinkes** [comment]
Google says this SocketException happens if the Application is located on a Network Shared Drive.
Seems to be specifically related to SMBv1 Drives.

See:
- https://stackoverflow.com/questions/50466688/a-non-recoverable-error-occurred-during-a-database-lookup-on-windows-7-with-kb#comment92037982_52526074
- https://social.msdn.microsoft.com/Forums/vstudio/en-US/4ffd2bcb-00fd-4518-a77d-a5825a3a9d7a/error-using-the-functions?forum=wcf

**Comment by shawndewet** [comment]
I noticed that, but didn't think it could apply...the app is running in debug mode on my local Windows C: drive.
The same error comes up if I launch the local exe (and also tried running it as Administrator).

**Comment by shawndewet** [comment]
I've determined that the problem is an `@` symbol in the host name.
I was given a hostname of the following structure:
`[some private info here]@ssh.eu-5.magento.cloud`

When I remove everything up to and including the `@` symbol, the error is avoided.

**Comment by h30h30** [comment]
Thanks man I had same error with when I was using a ssh vpn app in windows (Respite) and this comment comes from nowhere and helped me :))
