### ISSUE TITLE
Connection error on Linux Mono

### ISSUE THREAD

**Issue by Joannick** [sshnet/SSH.NET#828]
Hi,
I'm using Renci.SSH nuget on a C# Project running on Mono (Mono JIT compiler version 5.18.0.240 (Debian 5.18.0.240+dfsg-3 Wed Apr 17 16:37:36 UTC 2019)) 
The message is "The method or operation is not implemented" Into the function WaitOnHandle un Connect class. 
Is there an issue about this ? 
Thanks

**Comment by m0ivq** [comment]
I can confirm the same error also - for me this happens when using a RaspberryPi OS client running mono attempting to connect to an Onion SoC module host running OpenWRT 22.03 but used to run fine when connecting to the same device running OpenWRT 18.06.

However, running the same application on a windows client connecting to the same host device running OpenWRT 22.03 works fine.

Something seems to have changed regarding SSH hosts on later Linux distros but only affects SSH.NET when running on a Linux client under Mono.

**Comment by darkoperator** [comment]
More than likely it is the new ciphers, the library is very limited in the ciphers it supports and most Linux distros are moving to newer ones Sent from my iPhoneOn Feb 16, 2023, at 5:51 PM, Simon ***@***.***> wrote:﻿
I can confirm the same error also - for me this happens when using a RaspberryPi OS client running mono attempting to connect to an Onion SoC module host running OpenWRT 22.03 but used to run fine when connecting to the same device running OpenWRT 18.06.
However, running the same application on a windows client connecting to the same host device running OpenWRT 22.03 works fine.
Something seems to have changed regarding SSH hosts on later Linux distros but only affects SSH.NET when running on a Linux client under Mono.

**Comment by m0ivq** [comment]
@darkoperator yep you appear to be correct. Using the workaround in #807 to remove ECDSA keys has got my code working again in mono. The problem is actually with Mono and not SSH.NET so this issue should be closed.

**Comment by Rob-Hague** [comment]
Should be fixed by #1461
